### ISSUE TITLE
Help needed!!

### ISSUE THREAD

**Issue by DerGoogler** [Magisk-Modules-Alt-Repo/mkshrc#5]
## Workaround to initialize other app environment

- `su`
- `ppsu yarolegovich.materialterminal`

> What does mean `ppsu`?
> "Per-package switch user", small to written by me to switch to an user by the package name. Also good utility to initialize other app environment

This does not still fix the issues that `/dats/chuser/*` is unwriteable

# Issue
Seems that Android 13 has other `/data` permission and owner. Please execute the command below and share the text file/content with me or here.

```shell
ls -l / | grep -E 'data' > /sdcard/data_property.txt
```

Additional information should be added:

- Android version that are you using currently
- which rom you currently using (LOS, PE, etc...)
- optional phone

I need these information to expose if an non-root app can access the `/data/chuser` folder. Since I upgraded to Android 13, having problem creating non-root app thier environment.

## Screenshot
![Screenshot_20230115-205951_Material Terminal](https://user-images.githubusercontent.com/54764558/212564589-746e6703-0c7c-40ad-b7d7-238c1d90e82f.png)

**Comment by ARASAKA69** [comment]
@CRANKV2 (Telegram)

Android 13
Unbound Rom 2.0
Samsung Galaxy S20
[data_property.txt](https://github.com/Magisk-Modules-Alt-Repo/mkshrc/files/10421145/data_property.txt)

**Comment by DerGoogler** [comment]
Thanks, @HuskyDG for your help!
