### ISSUE TITLE
Constant root

### ISSUE THREAD

**Issue by Pro2stinger** [Magisk-Modules-Alt-Repo/mkshrc#8]
When a normal app uses `sh` or `bash` mkshrc will instantly request root access. Could you change this and make it so that it doesn't need root (by giving `/data/mkuser` `1777` permissions and the individual home folders user specifc ones)

**Comment by DerGoogler** [comment]
Sorry for the late reply. After first installation you are need to run as root first, then the module will create the work dir, etc..

What do you mean with giving the home folders specific one?

For KernelSU you'll need to configure this module also in the KernelSU Manager

**Comment by Pro2stinger** [comment]
> Sorry for the late reply. After first installation you are need to run as root first, then the module will create the work dir, etc..
> 
> What do you mean with giving the home folders specific one?
> 
> For KernelSU you'll need to configure this module also in the KernelSU Manager

Yeah sorry. This was for an older version. It has changed now.
